FROM python:3.13-slim

WORKDIR /app

COPY bp_flask_app.py ./
COPY blood_pressure_tracker.py ./
COPY bp_flask_utils.py ./
COPY requirements.txt ./

# Install system dependencies for ARM
RUN apt-get update && apt-get install -y libpq-dev gcc

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "bp_flask_app.py"]
